

= Meeting notes : documentation for ARGO 25/04
Cécile Marc <cecile.marc@b-com.com>

= Participants
* Cécile Marc
* Jérôme Royan
* Etienne Besson
* Azdine Tadrist
* Jean-Bernard Rault

== Introduction

The objective of the meeting is to expose ARGO needs concerning documentation to SFT, and see with SFT if :
 ** if similar problematics have been encountered (and solved by other bcom projects)
 ** existing solutions about documentation in openSource

 Le document suivant ici a été présenté pour exposer les besoins d'ARGO en terme de doc .
 Voici le document partagé https://forge.b-com.com/plugins/docman/?group_id=251&action=show&id=955

== Wich OpenSource platform

Etienne nous pose la question du choix de la plateforme OpenSource (OpenStack, Gitlab). C'est une question sur laquelle on ne s'est pas encore penchés
 ** un peu de veille sur les différentes PF OpenSource à réaliser

== Versioning de la doc en ligne

Etienne nous a demandé quel était notre besoin en terme de versioning.
*** Question à creuser !

== Versioning de la doc selon la solution choisie
* Côté MEDIAWIKI  : ?
* Côté site web, ce sont en général les sources du site web (en cas de site style web app, ce n'est donc pas les pages html qui sont versionnées).
* Dans ARGO, a priori on aura un site web statique  (pas de compilation pour générer le html) ?
*** point à vérifier
* En OpenSource, en général la doc est faite en mode texte style RST ou adoc, et ce sont ses sources qui sont versionnées. Un site web est généré pour obtenir du HTML. et l'héberger sur un serveur web.
Du coup en OpenSource une modification de documentation est réalisée grâce à un PULL request.
C'est aussi faisable d'avoir un mediawiki mais cela pose la problématique de la gestion des droits (à gérer en plus).



== Proposition
Une solution proposée par SFT est d'utiliser les outils Jekylls pour le framework de notre site web.
Nous gèrerons alors nos sources de documentations au format adoc (ou RST) dans GIT.
En mettant en place un outil d'intégration continu comme JENKINS dans ARGO, on intégrera aussi la mise à disposition de la documentation sur serveur web.
JENKINs peut être intégéré à l'extérieur pour les projets OpenSource , b<>com l'a déjà fait.

* Proposition acceptée par ARGO ? a priori oui, à discuter en équipe ARGO.

== Bascule Mediawiki vers adoc (pour site web)
L'outil PANDOC permet de faire la conversion à 80%, il faut s'attendre à un peu d'adaptation pour ce qui pose problème. (prévoir du temps/ressources)

== Outils qui peuvent nous servir
* PANDOC
* JEKYLL
* ASCIIdoctor
* ASCIIdoctormathematical
* plugin asciidoc pour firefox
* ATOM
* graphviz?
* Autres?


== Next steps
 * Equipe ARGO : fournir un plan/ structure de notre site web pour que SFT puisse nous proposer un outil Jekyll avec une structure de site web qui nous convienne.
 Design du site Web
 * Equipe ARGO (plus tard) : conversiion à prévoir (PANDOC + à la main) et moment de bascule à prendre en compte par tous (ne pas modifier mediawiki et sources asciidoc en même temps)
 * Equipe ARGO : voir comment on gérera la doc sous GIT. Est-ce qu'une branche master sera suffisant?
 * Equipe SFT: en attente de nos retours sur ce sujet...


== autres contacts
FALCON a eu des problématiques similaires aux nôtres, ça peut être intéressant d'échanger avec Vincent Mahé
